src/component/index.ts, src/component/index_spec.ts, src/component/schema.d.ts, src/component/schema.json, src/module/index.ts, src/module/index_spec.ts, src/utils.ts
- default to '' (empty) extension for {N} only projects
- respect custom extensions for components
=> fix: specifying extensions

package-lock.json, src/ast-utils.ts, src/collection.json, src/module/index.ts, src/refactor-nsng-modules/index.ts, src/refactor-nsng-modules/index_spec.ts, src/refactor-nsng-modules/schema.d.ts, src/refactor-nsng-modules/schema.json, src/route-utils.ts, src/utils.ts
Replaces NativeScriptModule imports with NativeScriptCommonModule
imports in feature modules.
Removes NativeScriptAnimationsModule imports from feature modules and
adds import to that module in the root module.
Migration for the breaking change here - NativeScript/nativescript-angular#1196
=> feat: add schematic for fixing module imports in feature modules 

src/add-ns/index.ts, src/ng-new/application/_files/package.json, src/ng-new/shared/_files/package.json
The webpack packages required for the {N} build are now dependencies of the nativescript-dev-webpack plugin. We can now remove them from the project's package.json and stop running `npm i` twice when adding `nativescript-dev-webpack` to the project.
=> refactor: update to nativescript-dev-webpack 0.14.0

src/add-ns/_ns-files/__sourceDir__/app/__entryComponentName@dasherize__.component__nsext__.ts, src/add-ns/_ns-files/__sourceDir__/app/barcelona/player-detail/player-detail.component.ts, src/add-ns/_ns-files/__sourceDir__/app/barcelona/players/players.component.ts, src/generate/component/index.ts, src/migrate-component/index.ts, src/ng-new/shared/_files/__sourcedir__/app/app.component.ts, src/ng-new/shared/_files/__sourcedir__/app/barcelona/player-detail/player-detail.component.ts, src/ng-new/shared/_files/__sourcedir__/app/barcelona/players/players.component.ts
This PR removes `moduleId: module.id` from all components generated by code sharing schematics.
Also, `ng g c` will only add `moduleId: module.id` for `{N} Only` projects, but it won't do it inside code sharing projects
fixes #40
=> fix: module.id issue in code sharing projects

CHANGELOG.md, package.json
<a name="0.2.4"></a>
* **add-ns:** exclude {N} files from web tsconfig ([9792a54](https://github.com/nativescript/nativescript-schematics/commit/9792a54)), closes [#56](https://github.com/nativescript/nativescript-schematics/issues/56)
* introduce --sample flag for `ng add` ([3c05fe4b556adde214dc880d4957c970e700eeed](https://github.com/NativeScript/nativescript-schematics/commit/3c05fe4b556adde214dc880d4957c970e700eeed))
=> release: cut the 0.2.4 release

src/ng-new/shared/_files/__dot__gitignore
Add NativeScript `hooks` and `platforms` folders to the default `.gitignore` of a new shared project.
=> chore(ng-new): add hooks and platforms to shared .gitignore

package.json
The `test` script fails because it tries to execute `needle` specs from `node_modules`.
```
Error: ENOENT: no such file or directory, open '/Users/nsbuilduser/workspace/nativescript-schematics/node_modules/fsevents/node_modules/needle/test/keys/ssl.cert'
at Object.fs.openSync (fs.js:646:18)
at Object.fs.readFileSync (fs.js:551:33)
at Object.<anonymous> (/Users/nsbuilduser/workspace/nativescript-schematics/node_modules/fsevents/node_modules/needle/test/helpers.js:9:13)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm …
```
=> test: do not test node_modules specs

src/ast-utils.ts, src/generate/module/index.ts, src/generate/module/index_spec.ts, src/generate/module/schema.d.ts, src/generate/module/schema.json, src/generate/utils.ts, src/migrate-module/index.ts, src/migrate-module/index_spec.ts
- fix(module): stop generating common files in web/ns only cases
- test(module): add unit tests for ns-only schematic in shared project
- refactor(module): introduce a 'common' flag
- refactor(migrate-module): generate a common file when migrating
=> Extend module and migrate-module unit tests

package-lock.json, src/add-ns/_sample-files/barcelona/barcelona.common.ts, src/add-ns/_sample-files/barcelona/barcelona.module__nsext__.ts, src/add-ns/_sample-files/barcelona/barcelona.module__webext__.ts, src/generate-template/master-detail/_files-nsonly/__name__/__master__.module.ts, src/generate-template/master-detail/_files-shared/__name__/__master__.common.ts, src/generate-template/master-detail/_files-shared/__name__/__master__.module.__nsext__.ts, src/generate-template/master-detail/_files-shared/__name__/__master__.module.ts, src/generate/module/_files/__name__.common.ts, src/ng-new/shared/_sample-files/barcelona/barcelona.common.ts, src/ng-new/shared/_sample-files/barcelona/barcelona.module.tns.ts, src/ng-new/shared/_sample-files/barcelona/barcelona.module.ts
When declaring constants it's prefered to use lower camel case variable names (`heroRoutes`) instead of UPPER_SNAKE_CASE (`HERO_ROUTES`). https://angular.io/guide/styleguide#constants
=> refactor: rename constant variables to follow the Angular style guide

.gitignore, .vscode/launch.json, src/ast-utils.ts, src/generate/component/ast-utils.ts, src/generate/component/find-module.ts, src/generate/component/index.ts, src/generate/component/index_spec.ts, src/migrate-component/component-info-utils.ts, src/migrate-component/index.ts, src/utils.ts
Before we were delegating the task of declaring new components inside an NgModule to the external `component` schematic. However, this causes two problems:
- If a custom web extension is used for the web files (f.e. `app.module.web.ts`), the external schematic won't find an NgModule to declare the new component in. That's because the external schematic looks only for files ending with `.module.ts`.
- The component won't be declared inside the {N} module (`app.module.tns.ts`).
With these changes, the external component schematic is always called with `skipImport: true` and the new component is manually declared inside an appropriate NgModule (web, mobile or both).
The PR also adds a simple VSCode launch configuration for debugging unit tests.
fixes #78, #54
=> Manually import newly created components in the right NgModules

package-lock.json, package.json, src/add-ns/index_spec.ts, src/angular-json/index.ts, src/angular-project-parser.ts, src/app-resources/index.ts, src/generate/component/index.ts, src/generate/component/schema.json, src/generate/module/schema.json, src/ng-new/application/index.ts, src/ng-new/application/schema.json, src/ng-new/shared/index.ts, src/ng-new/shared/schema.json, src/styling/index.ts
- devkit and schematics dependencies are bumped to `0.8.0-rc.1`
- `architect` -> `targets` in angular.json
- `TemplateOptions` is moved from `@angular-devkit/schematics` to `@angular-devkit/core`
=> refactor: migrate to Angular CLI 6.2

src/migrate-component/_ns-style/__path__/__styleFileName@addNsExtension__, src/migrate-component/component-info-utils.ts, src/migrate-component/index.ts, src/migrate-component/index_spec.ts, src/migrate-component/schema.d.ts, src/migrate-component/schema.json, src/migrate-module/index.ts, src/migrate-module/index_spec.ts, src/migrate-module/schema.d.ts, src/migrate-module/schema.json
use `--no-style` to skip the generation of [css | scss] files
=> feat: generate stylesheets when migrating components and modules

src/generate/component/index.ts, src/generate/component/index_spec.ts
this will make sure that when generating a component inside a folder, like:
`ng g c home/table`
The component name will ignore the folder name and keep only the name of the component =>`TableComponent` 
#134
=> fix: generate issues

package-lock.json, package.json
This PR bumps the versions of the Angular tooling dependencies. No changes in the code are needed.
=> refactor: update to Angular 7.1

src/add-ns/_ns-files/__sourceDir__/package.json, src/add-ns/_ns-files/tsconfig__nsext__.json, src/ng-new/shared/_files/__sourcedir__/package.json, src/ng-new/shared/_files/tsconfig.tns.json
This PR unifies the TypeScript configs for normal and code-sharing {N} apps. This should fix #173.
fixes #173
=> fix: resolve main.tns.ts with webpack's VFS instead with TS

.github/ISSUE_TEMPLATE/bug_report.md
Update the template for filing issues:
- ask for the content of the `package.json` instead of the versions of
specific packages;
- remove the note about attaching a sample project from the Playground,
because code-sharing projects are not supported there.
=> docs: update the bug report template

src/add-ns/index.ts, src/ng-new/shared/_files/package.json
The new npm script will allow devs to call `npm run preview`, which will execute `tns preview --bundle`
=> chore: add an npm script for tns preview

src/add-ns/_ns-files/nsconfig.json, src/models/nsconfig.d.ts, src/ng-new/application/_files/nsconfig.json, src/ng-new/application/index_spec.ts, src/ng-new/shared/_files/nsconfig.json, src/ng-new/shared/index_spec.ts, src/utils.ts
The schematics are creating projects with the legacy workflow.
The schematics are creating projects with the recommended Webpack + HMR workflow enabled by default as we do in all NativeScript 5.4 templates.
=> feat: use HMR by default for newly created projects

.gitignore, src/angular-project-parser.ts, src/convert-relative-imports/index.ts, src/decorator-utils.ts, src/generate-template/master-detail/index_spec.ts, src/generate/component/ast-utils.ts, src/generate/component/index_spec.ts, src/generate/module/index.ts, src/migrate-component/component-info-utils.ts, src/migrate-component/index.ts, src/migrate-component/index_spec.ts, src/migrate-module/index.ts, src/migrate-module/index_spec.ts, src/refactor-nsng-modules/index.ts, src/route-utils.ts, src/ts-utils.ts, src/utils.ts
The `utils.ts` module requires `typescript.` This causes all schematics requiring the `utils.ts` to also try to load `typescript` even if it's not needed. The `typescript` module is available when executing schematics in an Angular project because all Angular projects depend on `typecsript`. However, trying to load `typescript` when executing `ng new` will fail unless `typescript` is globally installed.
The TypeScript helper functions are moved to a separate `ts-utils.ts` file.
Fixes #216.
=> fix: move all typescript helpers to a separate file - `ts-utils`

src/add-ns/_ns-files/__sourceDir__/package.json, src/generate-template/master-detail/_files-nsonly/__name__/__detail__-detail/__detail__-detail.component.ts, src/generate-template/master-detail/_files-nsonly/__name__/__master__/__master__.component.ts, src/generate/component/ast-utils.ts, src/generate/component/index.ts, src/generate/component/index_spec.ts, src/ng-new/application/_files/__sourcedir__/home/home.component.ts, src/ng-new/application/_files/__sourcedir__/package.json, src/ng-new/application/_files/package.json, src/ng-new/shared/_files/__sourcedir__/package.json, src/ng-new/shared/_files/package.json, src/ts-utils.ts
* refactor: bump template versions to {N} 6.0
* refactor: set `markingMode` to `none`
* refactor: remove `moduleId` from component metadata
{N} 6.0 uses only webpack for building. When building Angular apps with
Webpack,the `module.id` is inserted automatically and we don't need to
set it manually. There's even a loader in `nativescript-dev-webpack` which removes the moduleIds from the source code.
In short, the `moduleId: module.id` is useful only for builds without webpack. NativeScript 6.0 doesn't support such builds. That's why we don't need moduleId in the templates anymore.
=> refactor: update to NativeScript 6.0

src/add-ns/_sample-files/barcelona/players/players.component__nsext__.html, src/generate-template/master-detail/_files-nsonly/__name__/__master__/__master__.component.html, src/generate-template/master-detail/_files-shared/__name__/__master__/__master__.component__nsext__.html, src/ng-new/shared/_sample-files/barcelona/players/players.component.tns.html
Fix no-dimension listview in stacklayout warning:
```
JS: Avoid using ListView or ScrollView with no explicit height set inside StackLayout. Doing so might results in poor user interface performance and a poor user experience.
```
=> fix: no-dimension listview in stacklayout warning

src/add-ns/index.ts
The `include` property overrides the `files` property, which is needed
for the AoT compilation.
=> refactor(add-ns): remove `include` property from web tsconfig

src/add-ns/index.ts, src/add-ns/index_spec.ts, src/ng-new/shared/_files/package.json
The `bundle` flag is no longer needed with {N} 6.0.
=> refactor(add-ns): remove `--bundle` flag from scripts

src/add-ns/_ns-files/tsconfig__nsext__.json, src/add-ns/index_spec.ts, src/ng-new/shared/_files/tsconfig.tns.json
In the current prerelease version, `*.android.ts` files are preferred over `*.ios.ts` files even when
building for iOS. To reproduce execute:
```
npm i @nativescript/schematics@0.6.1-2019-08-05-173433-01
ng new --shared --collection=@nativescript/schematics shared-project
cd shared-project/src/app
echo "console.log('ANDROID');" > print.android.ts
echo "console.log('IOS');" > print.ios.ts
echo "import '@src/app/print';" >> app.module.ts
tns run ios
```
As a result you will see `ANDROID` printed on the console, meaning that
the Android-specific file was imported even though we built the
application for iOS.
This behaviour is caused by the configuration of the `"paths"` property in
`tsconfig.tns.json`, which tells the TS compiler to look for
`*.android.ts` files first:
```
"compilerOptions": …
```
=> fix-next: stop preferring android-specific files over ios-specific files

package.json, src/ng-new/application/_files/package.json
The `@nativescript/schematics` package uses TypeScript utility functions from `@schematics/angular`. The utility functions return ASTs generated from the source code. After that these ASTs are used by other functions in `@nativescript/schematics`.
`@nativescript/schematics` depends on the version of TypeScript used in the project, whereas `@schematics/angular` has its own dependency on TypeScript. If the versions of the two TypeScript packages don't match, we end up comparing ASTs generated from different TS versions which usually results in an error.
This PR removes the dependency of `@schematics/angular` from the `@nativescript/schematics`. That way, the version in the user's project will be used instead. We rely on the assumption that the project will have matching versions of …
=> fix: make `@schematics/angular` a `devDependency` and update to Angular 8.2

src/angular-project-parser.ts, src/convert-relative-imports/index.ts, src/decorator-utils.ts, src/generate/component/ast-utils.ts, src/mapped-imports-rule-utils.ts, src/migrate-component/component-info-utils.ts, src/refactor-nsng-modules/index.ts, src/route-utils.ts, src/ts-utils.ts
The `@nativescript/schematics` package uses TypeScript utility functions from `@schematics/angular`. The utility functions return ASTs generated from the source code. After that these ASTs are used by other functions in `@nativescript/schematics`.
`@nativescript/schematics` depends on the version of TypeScript used in the project, whereas `@schematics/angular` embeds its [own version of `typescript`](angular/angular-cli:packages/schematics/angular/utility/ast-utils.ts@master#L8). If the versions of the two TypeScript packages don't match, we end up comparing ASTs generated from different TS versions which usually results in an error. Currently, we rely on the assumption that the project will have matching versions of `@schematics/angular` and `TypeScript`.
With this PR, the code using …
=> fix: use typescript from @schematics/angular

src/add-ns/index_spec.ts, src/ng-new/shared/_files/tsconfig.spec.json, src/ng-new/shared/index_spec.ts
Currently when new code shared app is created, `tsconfig.spec.json` is created with incorrect content. It is looking for one directory up for its base `tsconfig.json` file. Actually both `tsconfig.spec.json` and `tsconfig.json` files are at the root level of the application.
Rel to: https://github.com/NativeScript/nativescript-schematics/issues/243
`ng test` command doesn't work for code shared applications
`ng test` works for code shared applications
=> fix: extends correctly tsconfig.json from tsconfig.spec.json

package.json, src/ng-new/application/_files/tsconfig.json, src/ng-new/shared/_files/tsconfig.json
`Cannot find type definition file for 'jasmine/v2'` error is thrown when a new code shared application is created. It seems the issue comes [from this commit inside jasmine repo](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38412/files#diff-704f3d6b17350ee2426b25280154df4f).  Adding `skipLibCheck: true` to `tsconfig.json`  will skip the checks of `.d.ts` files inside `node_modules`. This will also improve the performance of typescript compilation with a lot of deps and files to process.
Rel to: https://github.com/NativeScript/nativescript-schematics/issues/249
=> fix: don't check the `.d.ts` files from `node_modules`

CHANGELOG.md
=> release: cut the 0.7.2 release

src/collection.json, src/generate/common-module/_files/__name__.common.ts, src/generate/common-module/index.ts, src/generate/common-module/schema.d.ts, src/generate/common-module/schema.json, src/generate/module/index.ts, src/generate/module/index_spec.ts, src/migrate-module/_ns-files/__name@dasherize__.module__nsext__.ts, src/migrate-module/index.ts
Let's say that you execute the command:
```
ng g migrate-module about
```
**Before this PR:**
- The `migrate-module` schematic uses the `module` schematic to generate a NgModule with `name='about'`;
- the `module` schematic filters out the files that end with `about.module.ts` - this is done because otherwise the we'll get a merge conflict;
- the `module` schematic uses the external `@schematics/angular module` schematic to generate `about.module.ts`;
- the `migrate-module` schematic renames `about.module.ts` to `about.module.tns.ts`.
Unfortunately, the `filter` function visits all files in `node_modules` and `platforms` and slows down the execution of the `module` schematic significantly. 
**With this PR:**
- The `migrate-module` schematic generates a NgModule file from a template …
=> fix: stop using filter in module generation schematic

src/angular-project-parser.ts, src/generate/component/index.ts
The  `ng add @nativescript/schematics` works only when using `css` styles within the web application. This PR gets the styles from `angular.json` and sets them to the `styleext` option. This way, the styles are respected when adding the auto-generated component.
Rel to: https://github.com/NativeScript/nativescript-schematics/issues/238
=> fix: convert web application to code-shared when using scss or less styles

src/add-ns/index.ts, src/ng-new/application/_files/package.json, src/ng-new/shared/_files/package.json
Currently, new-add and ng-new doesn't use the latest config required by `tns preview`. 
For example `tns preview` doesn't load `styles.css`
Uses the correct dependencies required by {N} 6.1
=> Update ng-add and ng-new to {N} 6.1

src/add-ns/_ns-files/__sourceDir__/app.css, src/add-ns/index.ts, src/add-ns/index_spec.ts, src/ng-new/application/_files/__sourcedir__/home/home.component.html, src/ng-new/application/_files/package.json, src/ng-new/shared/_files/package.json, src/styling/_css-files/app.css, src/styling/_scss-files/_app-variables.scss, src/styling/_scss-files/app.android.scss, src/styling/_scss-files/app.ios.scss, src/styling/index_spec.ts
=> feat: support for @nativescript/theme v2

package.json, src/app-resources/_files/__name__/Android/values-v21/styles.xml, src/app-resources/_files/__name__/Android/values-v29/styles.xml
Rel to https://github.com/NativeScript/nativescript-schematics/issues/269
=> fix: fix the dark mode support

src/add-ns/index.ts, src/ng-new/application/_files/package.json, src/ng-new/shared/_files/package.json
Currently `@nativescript/schematics@~0.7.0` is added as dependency to the project, so when a new project is created an old version of `@nativescript/schematics` is installed. Updating the version to `@8.0.0` will lead to an another problem that a version that is still not published to `npm` will be referenced within the project. In such a situation, the project should be created using `--skip-install` flag e.g `ng new --collection=@nativescript/schematics myApp --shared --skip-install`, after that the next version should be installed in the project before executing `tns run`.
=> fix: update version of `@nativescript/schematics` to `0.8.0` inside templates

package.json, src/add-ns/index.ts, src/ng-new/application/_files/package.json, src/ng-new/shared/_files/package.json, src/styling/_scss-files/_app-common.scss
When the application is created with `scss` styles, the theme is not applied due to the missing styles in `app.common` file.
=> fix: fix the theme when app is created with scss styles

src/ng-new/shared/_files/package.json
After creating a new project, when creating a component with 
```
ng new -c=@nativescript/schematics project-name --shared
ng g component bla
```
an error occurs:
```
Cannot read property 'kind' of undefined
```
No error occurs
Fixes/Implements/Closes #302
=> fix(angular): update typescript to version 4 for ng new

adding-angular-CLI-to-NativeScript.md, package.json, src/generate/utils.ts
1. `@schematics/angular` v11.1+ has introduced a breaking change where `@schematics/angular/utility/config` has been removed. `@angular/cli` v11.1+ seems automatically install these new versions. In v11.1+ version of `@schematics/angular`, getWorkespace method is instead at `@schematics/angular/utility/workespace` and is async now as pointed out at #311 by @avif. Using it requires a major codebase migration. Forcing this version (~11.0.0) via regular dependencies allows to continue using `@nativescript/schematics` with NG11.1 and NG11.2 projects, but further action should be taken before NG12 arrives.
2. There was a bug in the code generation utils by which every NS NG project counted as a shared project, thus generating web components in NS-only projects. The `isWeb()` utility function …
=> fix: CLI code generation in ng11.1+ NS-only projects

README.md, package.json, src/angular-project-parser.ts, src/generate/component/index.ts
1. ng generate component was not taking into account the style extension configured in angular.json file
2. TypeScript version should be 4.1 instead of 4.0 to work with `@schematics/angular@11.2`
3. Migration to `@schematics/angular@11.2` was partially done at `angular-project-parser.ts` file due to hidden `any` type errors.
With this angular.json file:
```json
{
"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
"version": 1,
"newProjectRoot": "projects",
"cli": {
"defaultCollection": "@nativescript/schematics"
},
"projects": {
"app": {
"root": "",
"sourceRoot": "src",
"projectType": "application",
"prefix": "Sym",
"schematics": {
"@schematics/angular:component": {
"style": "scss"
}
}
}
},
"defaultProject": "app"
}
```
In a NS project with TS 4.1.5, NS 7.3, and NG 11.2, it …
=> fix: lookup default stylesheet extension from angular.json file
